"use client";

import { Suspense } from "react";
import { MarketPage } from "./MarketPage";
import Spinner from "@/components/Spinner";

export default function Page() {
  const result = {
    message: "Security list fetched successfully",
    status: true,
    data: [
      {
        symbol: "JAIZBANK",
        lowPrice: 3.59,
        highPrice: 3.59,
        deltaChange: -0.01,
        totalValueTraded: 2173905,
        tradeVolume: 608205,
        high52Week: 3.64,
        low52Week: 1.9,
        openingPrice: 3.6,
        closingPrice: 0,
        prevClosingPrice: 3.6,
        weightedAveragePrice: 3.58,
        closingQuantity: 181123,
      },
      {
        symbol: "AVAIF",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -1000000,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 1000000,
        closingPrice: 0,
        prevClosingPrice: 1000000,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "ARADEL",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -530,
        totalValueTraded: 109451528,
        tradeVolume: 204949,
        high52Week: 850.1,
        low52Week: 401.1,
        openingPrice: 530,
        closingPrice: 0,
        prevClosingPrice: 530,
        weightedAveragePrice: 533.82,
        closingQuantity: 0,
      },
      {
        symbol: "VFDGROUP",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -58,
        totalValueTraded: 1542725,
        tradeVolume: 26732,
        high52Week: 58,
        low52Week: 40.1,
        openingPrice: 58,
        closingPrice: 0,
        prevClosingPrice: 58,
        weightedAveragePrice: 57.79,
        closingQuantity: 0,
      },
      {
        symbol: "HMCALL",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -5.88,
        totalValueTraded: 977840.44,
        tradeVolume: 167408,
        high52Week: 6.78,
        low52Week: 4.22,
        openingPrice: 5.88,
        closingPrice: 0,
        prevClosingPrice: 5.88,
        weightedAveragePrice: 5.84,
        closingQuantity: 0,
      },
      {
        symbol: "CONHALLPLC",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -3.65,
        totalValueTraded: 111373.5936,
        tradeVolume: 31000.9984,
        high52Week: 4.16,
        low52Week: 1.12,
        openingPrice: 3.65,
        closingPrice: 0,
        prevClosingPrice: 3.65,
        weightedAveragePrice: 3.61,
        closingQuantity: 0,
      },
      {
        symbol: "TRANSPOWER",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -364.9,
        totalValueTraded: 1725305,
        tradeVolume: 5250,
        high52Week: 386.4,
        low52Week: 264,
        openingPrice: 364.9,
        closingPrice: 0,
        prevClosingPrice: 364.9,
        weightedAveragePrice: 328.54,
        closingQuantity: 0,
      },
      {
        symbol: "NIDF",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -111.7,
        totalValueTraded: 1646160.5,
        tradeVolume: 14345,
        high52Week: 114,
        low52Week: 101.6,
        openingPrice: 111.7,
        closingPrice: 0,
        prevClosingPrice: 111.7,
        weightedAveragePrice: 114.84,
        closingQuantity: 0,
      },
      {
        symbol: "RESORTSAL",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "MULTITREX",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "VITAFOAM",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "ROYALEX",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "CADBURY",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "NASCON",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "UPL",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "STDINSURE",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "WEMABANK",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -1.28,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 1.28,
        closingPrice: 0,
        prevClosingPrice: 1.28,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "DUNLOP",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "STANBIC",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "AUSTINLAZ",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "CHAMPION",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "ABBEYBDS",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "CWG",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -5.48,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 5.48,
        closingPrice: 0,
        prevClosingPrice: 5.48,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "TRANSEXPR",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "UPDC",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "CAPHOTEL",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "ENAMELWA",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "VERITASKAP",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "GEREGU",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -100,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 100,
        closingPrice: 0,
        prevClosingPrice: 100,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "BUAFOODS",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -40,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 40,
        closingPrice: 0,
        prevClosingPrice: 40,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "GLAXOSMITH",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "DANGSUGAR",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "CUTIX",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "NB",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "IMG",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "UNHOMES",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "NAHCO",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "TRANSCORP",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "AIICO",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "AFRIPRUD",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "PRESTIGE",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "WAPIC",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "BUACEMENT",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -35,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 35,
        closingPrice: 0,
        prevClosingPrice: 35,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "MORISON",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "ELLAHLAKES",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "DAARCOMM",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "JOHNHOLT",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "MANSARD",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -2,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 2,
        closingPrice: 0,
        prevClosingPrice: 2,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "NOTORE",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -62.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 62.5,
        closingPrice: 0,
        prevClosingPrice: 62.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "PREMPAINTS",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "UCAP",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "AFROMEDIA",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "MEDVIEWAIR",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -1.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 1.5,
        closingPrice: 0,
        prevClosingPrice: 1.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "ABCTRANS",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "SOVRENINS",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "DEAPCAP",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "INTBREW",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "LEARNAFRCA",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "FIDELITYBK",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "ETERNA",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "UACN",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "TRIPPLEG",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "ETRANZACT",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "PHARMDEKO",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "CUSTODIAN",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "ARDOVA",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "REGALINS",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "NSLTECH",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "NNFM",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "UNIVINSURE",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "EKOCORP",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "MULTIVERSE",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "AFRINSURE",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "CORNERST",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "CONOIL",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "BETAGLAS",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "TOTAL",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "THOMASWY",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "MEYER",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "UBN",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "FLOURMILL",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "GTCO",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -28.55,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 28.55,
        closingPrice: 0,
        prevClosingPrice: 28.55,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "CILEASING",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "LIVESTOCK",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "SKYAVN",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -4.65,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 4.65,
        closingPrice: 0,
        prevClosingPrice: 4.65,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "LASACO",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "CAP",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "RTBRISCOE",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "ACADEMY",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "VANLEER",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "ETI",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -32,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 32,
        closingPrice: 0,
        prevClosingPrice: 32,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "NCR",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "ARBICO",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "ALEX",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "STERLINGNG",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -1.6,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 1.6,
        closingPrice: 0,
        prevClosingPrice: 1.6,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "JBERGER",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "STACO",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "HONYFLOUR",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "GOLDINSURE",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "LINKASSURE",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "FTNCOCOA",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "PZ",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "MRS",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "ASOSAVINGS",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "JAPAULGOLD",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "UNIONDICON",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "INTENEGINS",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "UNITYBNK",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "MAYBAKER",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "GUINEAINS",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "OANDO",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "NESTLE",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "GOLDBREW",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "NGXGROUP",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -16.15,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 16.15,
        closingPrice: 0,
        prevClosingPrice: 16.15,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "MBENEFIT",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "UNILEVER",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "TANTALIZER",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "OKOMUOIL",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "OMATEK",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "GUINNESS",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "CAVERTON",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -9.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 9.5,
        closingPrice: 0,
        prevClosingPrice: 9.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "FCMB",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "CHAMS",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "NPFMCRFBK",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "COURTVILLE",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "BERGER",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "NEM",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -1,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 1,
        closingPrice: 0,
        prevClosingPrice: 1,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "PRESCO",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "NEIMETH",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "SCOA",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "INFINITY",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -1.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 1.5,
        closingPrice: 0,
        prevClosingPrice: 1.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "SUNUASSUR",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "CHIPLC",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "TOURIST",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "EUNISELL",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "REDSTAREX",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "TRANSCOHOT",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -10,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 10,
        closingPrice: 0,
        prevClosingPrice: 10,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "IKEJAHOTEL",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "FIDSON",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "AIRTELAFRI",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -363,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 363,
        closingPrice: 0,
        prevClosingPrice: 363,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
      {
        symbol: "NIGERINS",
        lowPrice: 0,
        highPrice: 0,
        deltaChange: -0.5,
        totalValueTraded: 0,
        tradeVolume: 0,
        high52Week: 0,
        low52Week: 0,
        openingPrice: 0.5,
        closingPrice: 0,
        prevClosingPrice: 0.5,
        weightedAveragePrice: 0,
        closingQuantity: 0,
      },
    ],
  };
  return (
    <Suspense fallback={<Spinner />}>
      {" "}
      <MarketPage data={result.data} />
    </Suspense>
  );
}
